name: Slack

on:
  push:
    branches: [main]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Message to slack
    steps:
    - name: slack-send
    uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "Hello from GitHub action!"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
