name: Slack

on:
  release:
    types: [created]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Message to slack
    steps:
    - name: slack-send
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "*New release on @polygence/components*",
            "attachments": [
              {
                "color": "#f2c744",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "${{ github.event.release.tag_name }} 🚀",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Type:*\nPaid Time Off"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Created by:*\n<example.com|Fred Enriquez>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*When:*\nAug 10 - Aug 13"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Type:*\nPaid time off"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Hours:*\n16.0 (2 days)"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Remaining balance:*\n32.0 hours (4 days)"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "<https://example.com|View request>"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
